Refactor action.yml: Update thresholds for code coverage and adjust conditions for job steps

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -32,11 +32,11 @@ runs:
       shell: bash
       run: ${{ inputs.UNIT_TESTS_COMMAND }}
 
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v5
-      if: success() || failure()
-      with:
-        report_paths: ${{ inputs.REPORT_PATH }}
+    # - name: Publish Test Report
+    #   uses: mikepenz/action-junit-report@v5
+    #   if: success() || failure()
+    #   with:
+    #     report_paths: ${{ inputs.REPORT_PATH }}
 
     - name: Code Coverage Report
       uses: irongut/CodeCoverageSummary@v1.3.0
@@ -50,10 +50,10 @@ runs:
         hide_complexity: true
         indicators: true
         output: both
-        thresholds: "60 80"
+        thresholds: "80 90"
 
     - name: Append coverage markdown to job summary
-      if: always()
+      if: success()
       shell: bash
       run: |
         # Append markdown coverage report to the GitHub Actions job summary if present
@@ -69,12 +69,13 @@ runs:
 
     - name: Add Coverage PR Comment
       uses: marocchino/sticky-pull-request-comment@v2
-      if: ${{ github.event_name == 'pull_request' }}
+      if: ${{ github.event_name == 'pull_request' && success() }}
       with:
         recreate: true
         path: code-coverage-results.md
 
     - name: SonarQube Scan
+      if: success()
       uses: SonarSource/sonarqube-scan-action@v5
       env:
         SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
